### ISSUE TITLE
Problems installing the MP3 package

### ISSUE THREAD

**Issue by pedrety** [jongwook/MP3.jl#16]
Hi, I'm having some problems installing the MP3 package. 
I'm using Julia v1.3 and running `Pkg.add("MP3")` launches this error:

```
ERROR: The following package names could not be resolved:
* MP3 (not found in project, manifest or registry)
Please specify by known `name=uuid`. 
```
I don't know what to do, any idea what is happening here?

**Comment by ssfrr** [comment]
This package is no longer maintained and isn’t in the published registry.
