### ISSUE TITLE
Any hope of seeing this working with Julia 1.4?

### ISSUE THREAD

**Issue by cormullion** [jongwook/MP3.jl#21]
Is it possible for this package to be upgraded to work with Julia 1.4? Or has it been deprecated?

**Comment by jongwook** [comment]
We have #20 pending merge, which you might want to try.

**Comment by cormullion** [comment]
Great, thanks, and that's good news. (And how do I add that branch to my environment?)

**Comment by jongwook** [comment]
In the Pkg REPL (Press `]` from Julia REPL), enter

```
add https://github.com/dms449/MP3.jl
```

And it should install the package directly from the PR author's github

We haven't tested the PR yet, and I'm seeing a build error while I try the above in my Julia 1.2 shell; YMMV.

**Comment by cbdavis** [comment]
The PR works for me on Julia 1.4.2
