### ISSUE TITLE
no project file

### ISSUE THREAD

**Issue by JannuSudhakar** [jongwook/MP3.jl#24]
trying `add https://github.com/JuliaAudio/MP3.jl`gives the following error: `could not find project file in package at https://github.com/JuliaAudio/MP3.jl`. Some googling has led me to conclude that this is due to an old way of handling the packaging system and the new system requires one to add something called a project file.

**Comment by MelkerClaesson** [comment]
I cloned the repo and it doesn't precompile either. There might be a lot more issues with this package. For now the simplest workaraound I found is to call ffmpeg to convert the mp3 into another format.

like
run(`ffmpeg -i input.mp3 output.wav`)
