### ISSUE TITLE
Is the project updated anymore?

### ISSUE THREAD

**Issue by clouds56** [jongwook/MP3.jl#26]
I'm not expert of Julia but I'd like to help here.
If the repo is unlikely to taking PR any time in the near future, shall I publish a fork of MP3.jl to the registry?

**Comment by jongwook** [comment]
Not sure how JuliaAudio's governed nowadays, but I'd definitely appreciate if you could take the lead keeping MP3.jl updated.

@ssfrr @rob-luke @bramtayl: would it be okay to add @clouds56 as a new maintainer of MP3.jl?

**Comment by rob-luke** [comment]
I'm happy to review PRs. I can see that one was opened 7 hours ago, I can review it tomorrow. But it's checks are failing. Please make the checks green and then ping me for review.

**Comment by clouds56** [comment]
@rob-luke Thanks for kindly reply and review!
Now checks are broken since the julia version in configuration is still 0.6, I could help port to github workflow as other libs like [SampledSignals](https://github.com/JuliaAudio/SampledSignals.jl) do.
But I think a migration of CI setup is necessary.

**Comment by bramtayl** [comment]
I'm happy to add maintainers if everyone else is on board

**Comment by rob-luke** [comment]
I suggest @clouds56 opens a Pr to fix the issue and get the CIs green (you can make changes to the CI in the Pr and update the Travis version etc).

It's good practice to have someone demonstrate a few successful PRs before making admin. But I think it's up to ssfr
